Server:
  RunMode: release
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExtension: .log
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: tool
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 1873887255@qq.com
  Password: xxx
  IsSSL: true
  From: 1873887255@qq.com
JwtToken:
  SecretKey: xx
  ExpirationTime: 43200